name: Debug

#on:
#  push:
#    branches: [ "main" ]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Decode Environment File"
        run: |
          pwd
          ls -la
          sudo echo "${ENV_SECRET// /}" | base64 --decode > .env
          ls -la
        env:
          ENV_SECRET: ${{ secrets.ENV_FILE }}

#      - name: Decode gpg store
#        run: |
#          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
#          mkdir $TMP_KEYSTORE_FILE_PATH
#          echo "${{ secrets.GPG_STORE }}" > your_keystore.jks.asc
#          echo "KEYSTORE_PATH=$TMP_KEYSTORE_FILE_PATH/your_keystore.jks" >> $GITHUB_ENV
#          echo "${{ secrets.GPG_STORE }}" > your_keystore.jks.asc
#          ls -l
#          gpg -d --passphrase "${{ secrets.GPG_PHRASE }}" --batch your_keystore.jks.asc > "$TMP_KEYSTORE_FILE_PATH/your_keystore.jks"
#
#      - name: Read var
#        run: |
#          echo "${{env.KEYSTORE_PATH}}"
#          keytool -keystore "${{ env.KEYSTORE_PATH }}" -storepass ${{ secrets.SIGNING_STORE_PASSWORD }} -list